Feature/update colour palette
ONSdigital/babbage pull request #537
Opened 2021-02-26 06:34 UTC by NoelleDL

### What

Update colour values based on new colour palette. 

### How to review

Go to chart config in Babbage and see old palette. Pull this branch and see new colour palette options (Primary, Extended, Alternate). 

### Who can review

@armstrongb and anyone else but me.

2021-02-26 08:30 UTC, dandwal commented on src/main/web/templates/handlebars/highcharts/config/base/base-chart-config.handlebars
> +        #206095,    // blue
Some of the colours listed have new ONS wide names, we should refer to them as these from now on.


```suggestion
        #206095,    // ocean-blue
```

2021-02-26 08:30 UTC, dandwal commented on src/main/web/templates/handlebars/highcharts/config/base/base-chart-config.handlebars
> +        #27A0CC,    // light blue
Sky-blue

2021-02-26 08:30 UTC, dandwal commented on src/main/web/templates/handlebars/highcharts/config/base/base-chart-config.handlebars
> +        #003C57,    // dark blue/navy
night-blue

2021-02-26 08:30 UTC, dandwal commented on src/main/web/templates/handlebars/highcharts/config/base/base-chart-config.handlebars
> +        #A8BD3A     // lime green
Spring-green

2021-02-26 08:30 UTC, dandwal commented on src/main/web/templates/handlebars/highcharts/config/base/base-chart-config.handlebars
> +        #206095,    // blue
ocean-blue

2021-02-26 08:30 UTC, dandwal commented on src/main/web/templates/handlebars/highcharts/config/base/base-chart-config.handlebars
> +        #27A0CC,    // light blue
sky-blue

2021-02-26 08:30 UTC, dandwal commented on src/main/web/templates/handlebars/highcharts/config/base/base-chart-config.handlebars
> +        #003C57,    // dark blue/navy
night-blue

2021-02-26 08:30 UTC, dandwal commented on src/main/web/templates/handlebars/highcharts/config/base/base-chart-config.handlebars
> +        #A8BD3A,    // lime green
spring-green

2021-02-26 08:30 UTC, dandwal commented on src/main/web/templates/handlebars/highcharts/config/base/base-chart-config.handlebars
> +        #206095,    // blue
ocean-blue

2021-02-26 08:30 UTC, dandwal commented on src/main/web/templates/handlebars/highcharts/config/base/base-chart-config.handlebars
> +        #27A0CC,    // light blue
sky-blue

2021-02-26 08:30 UTC, dandwal commented on src/main/web/templates/handlebars/highcharts/config/base/base-chart-config.handlebars
> +        #A8BD3A,    // lime green
spring-green

2021-02-26 10:30 UTC, armstrongb commented
Not all chart colours have a 'new palette' name so some legacy names may remain.

2021-02-26 10:36 UTC, armstrongb requested changes
LGTM with Dan's comments to be addressed.

2021-03-02 06:39 UTC, NoelleDL commented on src/main/web/templates/handlebars/highcharts/config/base/base-chart-config.handlebars
> +        #A8BD3A,    // lime green
Made these changes.

2021-03-02 08:34 UTC, armstrongb submitted a review, later dismissed
LGTM

2021-03-03 15:31 UTC, mwnicks approved these changes
Reapproving following rebase

2021-03-03 15:32 UTC, merged