Feature/upgrade handlebars
ONSdigital/babbage pull request #693
Opened 2023-08-30 13:34 UTC by lindenmckenzie

### What

Upgraded handlebars - I've taken it to 4.2.1 instead of 4.3.1 as handlebars-markdown is deprecated in 4.3.1

Due to Handlebars 4.3.1 using generic Object instead of CharSequences for the Helper.Apply I went through and changed all of them. 

Added explicit dependency for antlr4 in pom.xml.
Small bit of tidying.

Removed some excludes that are no longer relevant. 

I've added an exclude for guava because we have the same vulnerability already excluded for the elasticsearch dependency that we cannot upgrade. Therefore to remove it would be timeconsuming and gain no value. I tried overriding guava to the latest version but it introduces a lot of breaking changes. 

### How to review

Ensure Babbage is still rendering things. 

### Who can review

Not me - Java engineer likely, or a FE.

2023-09-05 09:28 UTC, mr-nick17 submitted a review, later dismissed
All good from a frontend perspective

2023-09-06 14:52 UTC, cookel2 requested changes
Two very small changes to make. But it all works correctly in my local environment.

2023-09-06 14:52 UTC, cookel2 commented on src/test/java/com/github/onsdigital/babbage/template/handlebars/helpers/resolve/DataHelpersTest.java
> +        Object resolve = mockDH.resolveTaxonomy.apply(uri, options);
The resolveTaxonomy field is static so it should be accessed using the class name:
```suggestion
        Object resolve = DataHelpers.resolveTaxonomy.apply(uri, options);
```

2023-09-07 13:52 UTC, cookel2 approved these changes
looks good to me

2023-09-07 13:55 UTC, merged